before:
  hooks:
    - go mod download
builds:
- id: covaccine-notifier
  binary: covaccine-notifier
  main: .
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
   - 5
   - 6
   - 7
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
- binaries:
  - controller
  image_templates:
  - 'ghcr.io/prasadg193/covaccine-notifier:{{ .Tag }}'
  dockerfile: 'Dockerfile'
